# Mapeia o CÓDIGO CURTO da regra para o ID numérico da empresa no Fortes.
# Este é o único dicionário que deve ser usado como fonte da verdade para os IDs das empresas.

CODE_TO_EMP_ID = {
    # Empresas com pagamento no Dia 15
    "ABF": 130,  # ABF DISTRIBUIDORA DE PRODUTOS DE LIMPEZA E ESCRITORIO LTDA
    "AMM": 4844,  # AMM SERVICOS DE APOIO ADMINISTRATIVO LTDA
    "CMD": 9200,  # C.M. DISTRIBUIDORA DE ALIMENTOS LTDA - MATRIZ
    "CSR": 4809,  # CSR FORNECIMENTO DE REFEICOES E SERVICOS EMPRESARIAIS LTDA
    "GON": 9141,  # GONCALES INDUSTRIA E COMERCIO DE PRODUTOS ALIMENTICIOS LTDA
    "IMI": 2047,  # INGRID MAIA EIRELI
    "LUBRINORTE": 9130,  # IMPORTADORA LUBRINORTE LTDA
    "MAP": 9135,  # M.A. DE O. PINHEIRO LTDA
    # TODO: Verificar ID para MTZ - S A ALIMENTOS E PRODUTOS REGIONAIS LTDA
    "TACACA": 9237,
    "PHY": 2021,  # PHYSIO VIDA - HYK SERVICOS DE FISIOTERAPIA E COMERCIO DE ARTIGOS ESPORTIVOS LTDA
    "REMBRAZ": 16,  # DISTRIBUIDORA COMERCIAL REMBRAZ EIRELI
    "RIO": 9179,  # FABRICACAO DE CERVEJAS E CHOPES RIO NEGRO LTDA
    "ROLL": 9100,  # ROLL PET INDUSTRIA E COMERCIO DE PLASTICOS LTDA
    "RPC": 9255,  # REAL PROTEINA COMERCIO DE CARNES LTDA
    "SUP": 4780,  # SUPPORT NORT COMERCIO DE EQUIPAMENTOS E COMPONENTES INDUSTRIAIS LTDA
    "UNI1": 2069,  # UNIMAR - AMAZONAS DESPACHOS ADUANEIROS EIRELI
    "UNI2": 10,  # UNIMAR - AMAZONAS DESPACHOS ADUANEIROS LTDA
    # Empresas com pagamento no Dia 20
    "ACB": 9234,  # A. C. B. LOCADORA DE VEICULOS LTDA
    "ANDREY": 9226,  # ANDREY E SOUZA SERVICOS DE CONSTRUCAO CIVIL LTDA
    "ASDAF": 41,  # A S DA FROTA E CIA LTDA
    "BBPE": 9186,  # BBPE SERVICOS DE CONSTRUCAO LTDA
    "BEL": 9225,  # BEL MICRO INDUSTRIAL LTDA
    "BERGA1": 9236,  # BERGA ONE COMERCIO DE PRODUTOS FARMACEUTICOS E HOSPITALARES LTDA
    "COPEF": 9180,  # COPEF CONSTRUCAO LTDA
    "EBRE": 9188,  # EMPRESA BRASILEIRA DE ENERGIA LTDA
    "JCR": 4819,  # GP SALMO 91 - JONIVAL COSTA RODRIGUES
    "JRRV": 4826,  # GP SALMO 91 - (MTZ) J R RODRIGUES VARIEDADES LTDA
    "JR": 9098,  # JR RODRIGUES DP
    "LMB": 92,  # LMB RESTAURANTES LTDA (MATRIZ 0001-37)
    "MASTER": 35,  # MASTERFOOD COMERCIO DE ALIMENTOS LTDA. (MATRIZ 0001-00)
    # TODO: Verificar ID para MTZ - ICM INDUSTRIA E COMERCIO DE METAIS LTDA (ID antigo: 5388)
    "MTZ-ICM": 537,
    # TODO: Verificar ID para MATRIZ - NEYMARX COMERCIO DE MATERIAIS LTDA (ID antigo: 4104)
    "NEYMARX": 4794,
    "NEWEN": 9224,  # NEWEN CONSTRUTORA E INCORPORADORA LTDA
    "PROJECONT-TAX": 9213,  # PROJECONT TAX SERVICOS DE RECUPERACAO
    "PV": 9193,  # PV COMERCIO ATACADISTA DE MAQUINAS E EQUIPAMENTOS LTDA
    "REAL": 37,  # REAL COMERCIO DE ARTIGOS DE ARMARINHO LTDA
    # TODO: Verificar ID para GP SALMO 91 - (MTZ) R DE S RODRIGUES VARIEDADES LTDA (ID antigo: 4148)
    "RSR": 4148,
    "SOLAPOWER": 2142,  # SOLAPOWER SERVICOS DE ENGENHARIA E MANUTENCAO LTDA
    "TET-GESTAO": 9128,  # T E T GESTAO EMPRESARIAL LTDA
    "TET-MTZ": 9131,  # MTZ - T E T COMERCIO E INDUSTRIA DE HORTIFRUTIGRANJEIROS LTDA
    "TKA": 4814,  # T K A DE SOUZA
    "TPA": 4835,  # T P A DE SOUZA
    "TRANSF": 9189,  # TRANSFORMAR LOCACAO DE VEICULOS E SERVICOS AMBIENTAIS LTDA
}
